import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  schema: [
    './src/db/schema/roles.ts',
    './src/db/schema/users.ts',
    './src/db/schema/firehose.ts',
    './src/db/schema/topics.ts',
    './src/db/schema/replies.ts',
    './src/db/schema/reactions.ts',
    './src/db/schema/votes.ts',
    './src/db/schema/tracked-repos.ts',
    './src/db/schema/community-settings.ts',
    './src/db/schema/categories.ts',
    './src/db/schema/moderation-actions.ts',
    './src/db/schema/reports.ts',
    './src/db/schema/notifications.ts',
    './src/db/schema/user-preferences.ts',
    './src/db/schema/cross-posts.ts',
    './src/db/schema/onboarding-fields.ts',
    './src/db/schema/moderation-queue.ts',
    './src/db/schema/account-trust.ts',
    './src/db/schema/community-filters.ts',
    './src/db/schema/account-filters.ts',
    './src/db/schema/ozone-labels.ts',
    './src/db/schema/community-profiles.ts',
    './src/db/schema/interaction-graph.ts',
    './src/db/schema/trust-seeds.ts',
    './src/db/schema/trust-scores.ts',
    './src/db/schema/sybil-clusters.ts',
    './src/db/schema/sybil-cluster-members.ts',
    './src/db/schema/behavioral-flags.ts',
    './src/db/schema/pds-trust-factors.ts',
    './src/db/schema/pages.ts',
    './src/db/schema/plugins.ts',
    './src/db/schema/mod-notes.ts',
    './src/db/schema/topic-notices.ts',
    './src/db/schema/mod-warnings.ts',
  ],
  out: './drizzle',
  dialect: 'postgresql',
  entities: {
    roles: true,
  },
  dbCredentials: {
    url: process.env['DATABASE_URL'] ?? 'postgresql://barazo:barazo_dev@localhost:5432/barazo',
  },
})
